services:
  web:
    build:
      context: ./api
    command: /bin/bash -c ./entrypoint.sh
    volumes:
      - ./api:/api
    environment:
      - DB_URL=mysql+asyncmy://root:root@db:3306/testing?charset=utf8mb4
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  mqtt_app:
    build:
      context: ./mqtt_app
    command: python -m mqtt_app.main
    environment:
      - DB_URL=mysql://root:root@db:3306/testing?charset=utf8mb4
      - BROKER_ADDR=mqtt_broker
      - DEBUG_PRINT=true
    depends_on:
      db:
        condition: service_healthy
      mqtt_broker:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testing
    healthcheck:
      test: mysql -uroot -p$$MYSQL_ROOT_PASSWORD --execute "SHOW DATABASES;"
      interval: 7s
      timeout: 7s
      retries: 5
    ports:
      - 3306:3306

  mqtt_broker:
    image: emqx:latest
    container_name: mqtt_broker
    healthcheck:
      test: /opt/emqx/bin/emqx_ctl status
      interval: 7s
      timeout: 7s
      retries: 5
    ports:
    - "18083:18083"
    - "8883:8883"
    - "1883:1883"
