services:
  web:
    build:
      context: ./api
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/api
    ports:
      - 8000:8000

  mqtt_broker:
    image: emqx:latest
    container_name: mqtt_broker
    ports:
    - "18083:18083"
