services:
  web:
    build:
      context: ./api
    command: /bin/bash -c ./entrypoint.sh
    volumes:
      - ./api:/api
    environment:
      - DB_URL=mysql+asyncmy://root:root@db:3306/testing?charset=utf8mb4
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  mqtt_app:
    build:
      context: ./mqtt_app
    command: python main.py
    environment:
      - DB_URL=mysql://root:root@db:3306/testing?charset=utf8mb4
      - BROKER_ADDR=mqtt_broker
      - APP_DEBUG=true
    depends_on:
      - web

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testing
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 5s
      retries: 10
    ports:
      - 3306:3306

  mqtt_broker:
    image: emqx:latest
    container_name: mqtt_broker
    ports:
    - "18083:18083"
