"""adds table charger_sessions

Revision ID: 35a6e801cd17
Revises: 
Create Date: 2023-06-24 11:17:47.338524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a6e801cd17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charger_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('energy_delivered_in_kWh', sa.Integer(), nullable=True),
    sa.Column('duration_in_seconds', sa.Integer(), nullable=True),
    sa.Column('session_cost_in_cents', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charger_sessions')
    # ### end Alembic commands ###
